kas: patches: oe-core: backport SPDX dependency fix
meta-xilinx wants to pull in a slightly different version of util-linux,
which means that when we change builds between the qemuarm64 and kula
targets, they need slightly different SPDX data files. However, there
were cases where the SPDX files were not rebuilt on version changes,
resulting in errors like the following:

   ERROR: linux-xlnx-6.12.10+git-r0 do_create_spdx: Cannot find any SPDX file for recipe util-linux-native, True sstate:util-linux-native:x86_64-linux:2.40.4:r0:x86_64:12: sstate:util-linux-native::2.40.4:r0::12:

This change from oe-core master appears to resolve this issue.

Signed-off-by: Brenda Streiff <brenda.streiff@emerson.com>